SRC =\
 Activations.cpp\
 BaseLink.cpp\
 BaseLinkFF.cpp\
 BaseNeuralNet.cpp\
 BaseNeuralNetFF.cpp\
 BaseNeuron.cpp\
 BaseNeuronFF.cpp\
 BasePattern.cpp\
 BasePatternElem.cpp\
 BasePatternElemFF.cpp\
 BasePatternFF.cpp\
 BaseWeight.cpp\
 BaseWeightFF.cpp\
 LinkBProp.cpp\
 LinkBPropM.cpp\
 NeuralNetBProp.cpp\
 NeuralNetBPropM.cpp\
 NeuronBProp.cpp\
 NeuronBPropM.cpp\
 NNSimService.cpp\
 PatternBProp.cpp\
 PatternElemBProp.cpp\
 WeightBProp.cpp\
 WeightBPropM.cpp\
