SRC =\
 basemem.cpp\
 bot_client.cpp\
 bot.cpp\
 bot_cs.cpp\
 bot_names.cpp\
 bot_wpdir.cpp\
 bot_wpstat.cpp\
 CBotBase.cpp\
 CBotCS_combat.cpp\
 CBotCS.cpp\
 CBotCS_navigate.cpp\
 CBotDOD_combat.cpp\
 CBotDOD.cpp\
 CBotDOD_navigate.cpp\
 CCommand.cpp\
 ChatBot.cpp\
 Chat.cpp\
 ChatHost.cpp\
 ChatHostData.cpp\
 CLTMem.cpp\
 Commandfunc.cpp\
 CParser.cpp\
 CPersonality.cpp\
 CRadio.cpp\
 CSDecals.cpp\
 CSkill.cpp\
 CState.cpp\
 CSTMem.cpp\
 CTask.cpp\
 dll.cpp\
 engine.cpp\
 Gnome.cpp\
 h_export.cpp\
 linkfunc.cpp\
 LListElem.cpp\
 namefunc.cpp\
 NNWeapon.cpp\
 util.cpp\
 waypoint_advdataimpl.cpp\
 waypoint.cpp\
 WorldGnome.cpp\
